"""`ptq site`: every page renders, links between pages stay on the site, links to other
repo files go to GitHub, charts come along, and no Markdown link survives."""

from __future__ import annotations

import re

import pytest

from ptqbench import site as S

pytestmark = pytest.mark.smoke


@pytest.fixture(scope="module")
def built(tmp_path_factory):
    out = tmp_path_factory.mktemp("site")
    pages = S.build(out)
    return out, pages


def test_pages_and_charts_are_written(built):
    out, pages = built
    names = {p.relative_to(out).as_posix() for p in pages}
    assert {"index.html", "results-guide.html", "how-it-works.html", "by-model/opt-125m.html"} <= names
    assert (out / "plots" / "opt-125m_perplexity.png").is_file()
    assert (out / ".nojekyll").is_file()


def test_links_stay_on_site_or_go_to_github(built):
    _out, pages = built
    for page in pages:
        text = page.read_text(encoding="utf-8")
        for href in re.findall(r'href="([^"]+)"', text):
            if href.startswith("http"):
                if href.endswith(".md"):
                    assert href.startswith(S.REPO_URL), (page.name, href)
                assert "/results/by-model/results/" not in href, "a link resolved from the wrong directory"
            else:
                assert not href.endswith(".md"), (page.name, href)
                target = (page.parent / href.split("#")[0]).resolve()
                assert target.is_file(), (page.name, href)
        for src in re.findall(r'<img[^>]+src="([^"]+)"', text):
            assert (page.parent / src).resolve().is_file(), (page.name, src)


def test_home_page_has_the_doors_and_the_table(built):
    out, _ = built
    index = (out / "index.html").read_text(encoding="utf-8")
    assert 'href="results-guide.html"' in index and 'href="how-it-works.html"' in index
    assert "<table>" in index and 'href="by-model/opt-125m.html"' in index
    assert "do not edit by hand" not in index


def test_how_it_works_keeps_its_diagram(built):
    out, _ = built
    page = (out / "how-it-works.html").read_text(encoding="utf-8")
    assert 'class="mermaid"' in page and "mermaid.esm.min.mjs" in page
    assert "flowchart TD" in page


def test_model_page_tables_and_footer(built):
    out, _ = built
    page = (out / "by-model" / "opt-125m.html").read_text(encoding="utf-8")
    assert page.count("<table>") >= 3 and 'src="../plots/opt-125m_perplexity.png"' in page
    assert "Generated by <code>ptq site</code>" in page and "results/raw/runs" in page


def test_link_rewriting_rules():
    md = "[guide](../README.md) [home](README.md) [design](../../docs/DESIGN.md) [web](https://x.y) [a](#top)"
    out = S._rewrite_links(md, "results/by-model/opt-125m.md", "by-model/opt-125m.html")
    assert "[guide](../results-guide.html)" in out and "[home](../index.html)" in out
    assert f"[design]({S.REPO_URL}/blob/main/docs/DESIGN.md)" in out
    assert "[web](https://x.y)" in out and "[a](#top)" in out
    img = S._rewrite_links("![c](../plots/x.png)", "results/by-model/m.md", "by-model/m.html")
    assert img == "![c](../plots/x.png)"
